### ISSUE TITLE
IF default folder has Chinese，TDM cant save file。

### ISSUE THREAD

**Issue by pangyf10** [inbasic/turbo-download-manager#10]
In FF，tdm show me finish download，but I can't find it 。Also I can't open it in tdm tab，or open the folder。I have test FF41 FF42 FF44 on windows 10 64bit。
In FF，I choose “always save in downloads folds” or “always ask me", it act no different。
I open Resource monitor ，it show that tdm doesnt save anything to disk。。。。。 

I find it is because my default download folder has some Chinese character。Maybe it is windows has some alias，I can use the same folder by ”add a new job“，where the folder url is all ascii。

**Comment by pangyf10** [comment]
If it has Chinese character in “add a new job”，does not matter。but default folder cant work。Now ，I dont know what is exactly problem。but I think it maybe the alias。

**Comment by inbasic** [comment]
I changed the default download directory to a folder with Chinese characters on it and the downloader works fine. Can you provide more details on how to generate the bug?

**Comment by pangyf10** [comment]
when using a windows with Chinese default language， it has someting like user folder，default show C:>用户>Lily>桌面 or 此电脑>桌面，but if try to copy the url ，its C:\user\Lily\Desktop。I think ，this is the problem。registry ，I dont know a lot about it ，but I think it is 。

**Comment by inbasic** [comment]
So if you use the "browse" button in ”add a new job“ window and try to point it to your desktop the downloader fails?

**Comment by pangyf10** [comment]
No，it will work，will show c:\user\Lily\Desktop. but after "reset it ", downloader fails.

**Comment by inbasic** [comment]
Is your `browser.download.dir` preference set to a value? open a browser tab, go to "about:config" and search for the pref

**Comment by pangyf10** [comment]
yes, this value point to somewhere doesnt exist。I try to change firefox downloads seting in options，to “always saves to.....”，doesnt work, make me think not its about firefox config.

**Comment by inbasic** [comment]
> yes, this value point to somewhere doesnt exist

I am not sure if I got your point here. Does this mean if you select the "Choose ..." button on "about:preferences" page and select a folder, still the `browser.download.dir` points to a wrong location?

**Comment by pangyf10** [comment]
Sorry, I say too much . It should be all my fault, I just select the button but do not select a folder. I use a profile of firefox copy from another machine, default folder is in the machine.

**Comment by inbasic** [comment]
Okay then; anyhow, in the latest dev version, download directory detection is improved. And if the folder is wrong, then you should see an error in the log (press "i" button in the right side of the download)

https://github.com/inbasic/turbo-download-manager/blob/master/builds/packed/firefox.xpi?raw=true
