### ISSUE TITLE
start/stop、cancel/delete、information button is too small.

### ISSUE THREAD

**Issue by pangyf10** [inbasic/turbo-download-manager#12]
I use TDM in a 14'' laptop, in TDM tab ,the  three buttons in right of the progress bar is too small. It is not a easy way to use. When it  is downloading something, the left has a big button, at start I think its button to stop/start, but its not .

**Comment by inbasic** [comment]
In the new release, icons arrangement has been improved to better support touch screen devices,

![screen shot 2015-11-17 at 11 11 19](https://cloud.githubusercontent.com/assets/351062/11205365/72a45288-8d1c-11e5-96d8-4b9e2182c486.png)

Thanks for the report.
