### ISSUE TITLE
Filename already existing in downloads folder

### ISSUE THREAD

**Issue by TBuc** [inbasic/turbo-download-manager#13]
When a file with the same filename exists in the Downloads directory, the download manager fails to copy it to the Downloads directory, and does not alert the user about it.

A practical example of what happened to me:
1) Downloads the file (progress visible in the plugin window).
2) I SUPPOSE that at this point it tries to copy it from the temporary directory to the Downloads directory, but the second one already contains a file with the same filename.
3) It actually _does not_ copy the file to the Downloads directory.
4) Does not show anything in the plugin window: not download completed, neither download failure.

I've then tried to find the downloaded file, and i found it inside the plugin's temporary dir. In my case, it was:
C:\Users[myUserName]\AppData\Local\Google\Chrome\User Data\Default\Storage\ext[a long string]\def\File System\primary\p\00\
The filename was "000000". I just renamed the file to match its original name, and it works fine. So I think it's all about managing the renaming issue for duplicated filenames.

@inbasic I've just noticed there's a new version of FileSaver.js available. Maybe the issue's already been solved and just needs to be updated?

**Comment by inbasic** [comment]
@TBuc can you confirm the latest dev version fixes the problem,
https://github.com/inbasic/turbo-download-manager/blob/master/builds/packed/chrome.zip?raw=true

Are you familiar how to install a dev version?

**Comment by inbasic** [comment]
Please try the latest version, 0.1.10 and reopen if the bug persists.

**Comment by TBuc** [comment]
@inbasic sorry for not replying; I wasn't notified there were new comments.
I can confirm you that with v.0.1.10 the bug is fixed.
Thank you for your work!
