### ISSUE TITLE
Does this download manger use browser cookies when request the file ?

### ISSUE THREAD

**Issue by abdr1000** [inbasic/turbo-download-manager#14]
I am using android downloader programe sometimes when downloading with this app it doesnt dowload simply because it is need login cookies for acces file so i had to use firefox for downloading it doesnt provide resume multithread and sometimes i had to redownload several times because of unstable internet connection i tried some extensions but it seems to doesnt use cookies so it download internet page instead of file

**Comment by inbasic** [comment]
Please try 0.1.10 
https://addons.mozilla.org/en-US/firefox/addon/turbo-download-manager/versions/

It uses cookies.

**Comment by abdr1000** [comment]
Thanks and i want another thing if the browser close suddenly i cant find the last download to resume thanks alot

**Comment by inbasic** [comment]
Please open a new bug for this as it might take some time to support this feature.
