### ISSUE TITLE
Downloading file lost after Firefox is closed

### ISSUE THREAD

**Issue by jingyu9575** [inbasic/turbo-download-manager#20]
Turbo Download Manager 0.1.11.1 with Firefox 44.0a2.
After Firefox was closed and reopened, my half-downloaded Windows Server ISO was aborted and not shown in UI anymore. It would be better to automaticly continue the download.

**Comment by inbasic** [comment]
True, still TDM does not support resuming on restart. I'll update this when this feature is available.

**Comment by inbasic** [comment]
From version 0.3.0, TDM warns users about not closing Firefox when there is an active job. This is a temporary solution until the restoring implementation is completed and TDM can handle cross session resumes.
