### ISSUE TITLE
Download attempt fails at opengapps.org

### ISSUE THREAD

**Issue by anewuser** [inbasic/turbo-download-manager#21]
Click on the red download button on this page and choose the option to download it with your extension: http://opengapps.org/?api=6.0&variant=nano

I tried it 3 times with different download combinations, but the download didn't even start. Downloading the packages with the default Firefox manager worked normally.

**Comment by inbasic** [comment]
Based on the log window, seems like this server does not return file-size; that's the reason why TDM cannot allocate space and start the download. Basically in these cases, there is no advantage of using a download manager over the default download manager.

**Comment by anewuser** [comment]
It should start the download anyway because users won't be able to tell what's going on and will assume that your extension is buggy. In those cases, you could add some sort of icon or notice to tell people that the current download can't be accelerated.

**Comment by inbasic** [comment]
Using the latest version, I can download from http://opengapps.org just fine. Please reopen if you still have this issue
