### ISSUE TITLE
Turbo download manager not work.

### ISSUE THREAD

**Issue by lagun** [inbasic/turbo-download-manager#22]
firefox 42 32bit
i test on a clean profile, it not work and same problem.
tdm version 0.1.11.1.
watch my video to see my problem.
https://sendvid.com/gbyeoms8

**Comment by inbasic** [comment]
Can you sned me the link of the webpage.

**Comment by lagun** [comment]
http://www.filehorse.com/download-avast-antivirus/

**Comment by inbasic** [comment]
Seems like if you right click on the "If it doesn't **click here** to start it", then you can use TDM just fine.

**Comment by lagun** [comment]
yes,just fine but i curious something  why it not show choice? Download with Turbo download manager

**Comment by inbasic** [comment]
I am not sure why. I'll keep this open for further investment. Thanks for the report.

**Comment by inbasic** [comment]
Seems the server is fixed. Firefox now allows you to select TDM. Please reopen if you have another case
