### ISSUE TITLE
filename not recognized

### ISSUE THREAD

**Issue by 1cman** [inbasic/turbo-download-manager#23]
when I try to download a file by copying the URL directly or from the context menu of chrome with estension (Turbo Download Manager Helper), the file name is not recognized.
1) go in a site with Video to download
2) copy the url of video directly from page or right button of mouse on url of video from chrome.//download then copy.
3) open turbo-download-manager then click on +
4) insert data of download (the URL is automatically inserted)
the file is nominated no with his name but with estension name like mp4.mp4

**Comment by inbasic** [comment]
In the latest version (0.2.0), there is a new field when you add a job. You can now suggest the file name/extension. If download is sent from context menu though, TDM will decide the name for you.

Can you send a sample link with this problem?

**Comment by 1cman** [comment]
I have seen the new changes in version 0.2.0,  it,s already a big step forward, thank you.
However, for example, trying to download this video from vimeo, (I use Video Downloader Professional extension) ROADTRIP in Vimeo Staff Picks on Vimeo.mp4 https://skyfiregcs-a.akamaihd.net/exp=1452202215~acl=%2A%2F461929778.mp4%2A~hmac=0b9c4a997a2256571acc8e9bcc40a840ed2cfda7ef526a05140f7c736c9f956e/vimeo-prod-skyfire-std-us/01/160/6/150803501/461929778.mp4
the download start, then if I select the link from the download page of chrome with the right mouse button, to transfer it to DTM the download is transferred to TDM correctly but TDM rename the file 461929778.mp4 in other case rename the file with mp4.mp4 or video.mp4

**Comment by inbasic** [comment]
> ...to transfer it to DTM the download is transferred to TDM correctly but TDM rename the file 461929778.mp4 in other case rename the file with mp4.mp4 or video.mp4

Well, there is no way for the extension to detect the right file name when you transfer it from right click content menu. Normally the server is supposed to provide the file-name. If not, the extension tries to detect the name from URL (title=...). 

For this case, I would say the easiest way is to set the name manually from UI.

**Comment by 1cman** [comment]
In this case it would be useful not to start automatically download but open the screen of TDM job, so we could add the name

**Comment by inbasic** [comment]
In version 0.2.1, you can request a job to be added in the pause mode (check "download layer" checkbox). Also in this version you can rename a job when it is paused.

Maybe I can add a new item to Turbo Download Manager Helper extension to allow adding jobs in the pause mode. This way extension decides the name for you, if you prefer a new one, you can just modify the name from the UI.

**Comment by 1cman** [comment]
Thank you, fantastic!
