### ISSUE TITLE
Stopped working after yesterdays Nightly build

### ISSUE THREAD

**Issue by SLK350** [inbasic/turbo-download-manager#24]
Turbo Download Manager stopped working after yesterdays Nightly build. Icon and download window save option is missing.

**Comment by SLK350** [comment]
I think this is the fix that's causing problems. https://bugzilla.mozilla.org/show_bug.cgi?id=1220564

**Comment by inbasic** [comment]
Thanks for the report. It is now fixed on the dev version

https://github.com/inbasic/turbo-download-manager/blob/master/builds/packed/firefox.xpi?raw=true

To try, download the XPI file and drop it into your Firefox browser.

**Comment by SLK350** [comment]
Thanks, working now.
