### ISSUE TITLE
Configurable multithreading

### ISSUE THREAD

**Issue by shmutalov** [inbasic/turbo-download-manager#25]
Please, provide manual threads count setup in settings.

**Comment by inbasic** [comment]
The number of threads is persistent. Just set it once while adding a job. As soon as the job is submitted, the extension remembers the number of all further jobs.

Note that it is not recommended to use more than 5 threads for a job.

**Comment by shmutalov** [comment]
Sorry, there's been a misunderstanding here. I am talking about automatic job adding (Firefox addon). When I select the download link Firefox "download with" window pop ups, there is no way to prepare TDM job at this point. Personally, I need configure job while downloading. Or it is not possible?

**Comment by inbasic** [comment]
> When I select the download link Firefox "download with" window pop ups, there is no way to prepare TDM job at this point

In the latest dev version, it is possible to adjust the number of threads before adding a new job, https://github.com/inbasic/turbo-download-manager/blob/master/builds/packed/firefox.xpi?raw=true
![screen shot 2016-01-13 at 16 30 18](https://cloud.githubusercontent.com/assets/351062/12295599/472324c2-ba17-11e5-85d5-0879d37387ed.png)

> Personally, I need configure job while downloading. Or it is not possible?

It is still not possible at the moment. I have a plan to fix this though.
