### ISSUE TITLE
Downloading Issue over multiple sites

### ISSUE THREAD

**Issue by gxgani** [inbasic/turbo-download-manager#26]
For example, If I am downloading any large file (ROM in particular) the download stops half way through.

![](https://cobalt60.xyz/shared/Screen-Shot-2016-01-15-07-05-27.png)
Download link for the rom: http://forum.xda-developers.com/devdb/project/dl/?id=16219

Also, TDM doesn't start downloading from google drive.

**Comment by inbasic** [comment]
> Download link for the rom: http://forum.xda-developers.com/devdb/project/dl/?id=16219

This server limits the total number of connections you can have for a single download. To confirm, just add a new download. Pause it several time and you will see the download will fail.
There are two workarounds:
1. Start the download with just a single thread, so hopefully you will not reach the limitation.
2. Download the latest dev version, https://github.com/inbasic/turbo-download-manager/blob/master/builds/packed/firefox.xpi?raw=true. In this version you can modify download properties on the pause mode. Whenever you reach the limitation, change the URL with a new one.

> Also, TDM doesn't start downloading from google drive. 

This is known issue. I am working on it.

**Comment by inbasic** [comment]
The latest dev version introduced a new feature. Now you can have multiple mirrors for a single download. If one mirror fails, the downloader removes it from the list and uses the other mirrors. I think this features will solve your issue with http://forum.xda-developers.com/devdb/project/dl/?id=16219

https://github.com/inbasic/turbo-download-manager/issues/28

**Comment by inbasic** [comment]
I am closing this as the latest version seems to be able to resume the download by introducing a fresh link
