### ISSUE TITLE
New job won't add manually

### ISSUE THREAD

**Issue by SailorOnDaTea** [inbasic/turbo-download-manager#27]
After update, It won't allow me to start/add a new download manually.
It gives warning for setting download directory but "browse" or "reset" buttons are not responding. I can't set folder.
![image](https://cloud.githubusercontent.com/assets/10913460/12536418/0a966764-c2ad-11e5-8ef6-349381f57701.png)

**Comment by inbasic** [comment]
Thanks for the report. I have just submitted a patch. The "Save in" line should no be displayed in the Opera version.

**Comment by SailorOnDaTea** [comment]
Thanks! I replaced files in extensions folder and it is working again now!
