### ISSUE TITLE
Mirrors

### ISSUE THREAD

**Issue by SailorOnDaTea** [inbasic/turbo-download-manager#28]
Some pages provide a number of mirrors, content distribution network links and sometimes each of them support only one connection. Thus, despite there are many sources that could be used in parallel, we are still stuck with single link.
Is it possible to download single file from many mirrors? Like this one for example:

![image](https://cloud.githubusercontent.com/assets/10913460/12582459/eee911d4-c445-11e5-84a1-8d2aebc9bbf6.png)

**Comment by inbasic** [comment]
This will be available on version 0.2.2
![screen shot 2016-01-27 at 13 58 40](https://cloud.githubusercontent.com/assets/351062/12610634/191d2162-c4fe-11e5-9120-06ae485e47f4.png)

Let me know your browser and I'll provide you with the instruction to check the developer version

**Comment by SailorOnDaTea** [comment]
=D nice! 

I use 32bit Opera v34 on win7x64

**Comment by inbasic** [comment]
You can try the latest dev version for Opera here
https://github.com/inbasic/turbo-download-manager/blob/master/builds/packed/opera.zip?raw=true

Download the zip file, extract in somewhere. Open `chrome://extensions/` page and check developer mode on. Now point "Load unpacked extension" to the extracted archive.

**Comment by inbasic** [comment]
Just one note. Opera version stores the entire file on RAM and writes the whole thing when the file is downloaded. Make sure you are not downloading large files with the extension. For large files use Chrome or Firefox version instead.

**Comment by SailorOnDaTea** [comment]
Yes I know it uses RAM, better than temp files on disk. I like that. Large files often disconnects so i use external download manager for them. I like this extension for quick fetching. I got 8GB of RAM so I think if I needed I could use 64bit browser.

I installed this and added mirrors but I am getting "doesn't support multi threading" error.
For example, this dictionary file(for test purpose):

```
http://www.lingoes.net/en/dictionary/dict_down.php?id=4E82D56B9DD6534086A293F2C553626B
```

When I download with browser, both links work(one by one).
I tried thread numbers 1,2,4,6. No luck.

Btw, is that thread count is for "per server" or "total" number?

**Comment by inbasic** [comment]
Well, some servers do not accept multi-threading (ranging). So there is no point for the TDM to test the mirrors. Try with another server. In the log window, you should have `Server multi-threading support status is **true**`.

For test purpose, you can add a single link and mark "Download Later" while adding the new job. Once the information is fetched, the extension auto pauses the download. Now click on the "download properties" button. You can add a mirror from there as well. After submitting the form with a new URL, log window will be updated in a few seconds notifying you whether this mirror is accepted or not.

> Btw, is that thread count is for "per server" or "total" number?

Total, if there are more than one links, the TDM rotates them to have equal distribution over all servers.

**Comment by SailorOnDaTea** [comment]
I see. Value is "false". So whole thing just won't work due to server behavior… whether or not adding mirrors won't make difference.

well… thanks for your effort. I guess there that is all to be done.
