### ISSUE TITLE
How to change the toolbar icon using stylish in firefox?

### ISSUE THREAD

**Issue by 70599** [inbasic/turbo-download-manager#29]
I wish to change the toolbar icon into

```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAtUlEQVQoz4XRO67CQAyF4U+JRBNITz+hpSIiBZNZCrthJ+yBarZGkQeT6ErXrqzzy49jlmgEvSjqBY1NVDqjVOToovrJV0kUtGq1VhAl1wXpJIPjpufRIOmm2aO4yllekWjUEBZyB0ydA72k/RNoJT1R+u27ASpJLIGXPOcL1JJHOeLsI8s+zuuI27RkmJs+ZdlzrmalPPPg7e2wPXNr1N2wN6q0+qRWO+2t/vdZ5btHD7fy3V9JyCcI+KNxbwAAAABJRU5ErkJggg==
```

Thanks.

**Comment by inbasic** [comment]
What is the problem with the current icon? Can you provide an screenshot

**Comment by 70599** [comment]
The current icon is 18px \* 18px, but displayed as 16px \* 16px.
I using the css below to make it 18px

```
.toolbarbutton-icon[label="Turbo Download Manager"] {
    min-width: 18px;
    height: 18px;
}
```

---

Before(16px):
![2016-02-04 1 31 58](https://cloud.githubusercontent.com/assets/5929170/12790935/b41c4d28-cadf-11e5-8a5c-48408f8c9ae4.png)

After(18px):
![2016-02-04 1 31 45](https://cloud.githubusercontent.com/assets/5929170/12791011/08b9ae20-cae0-11e5-8ebe-a82dc8cb1098.png)

**Comment by inbasic** [comment]
https://developer.mozilla.org/en-US/Firefox/Australis_add-on_compat

> internal icons on the navbar use 18px. For add-ons, by default the padding is set up so it should work well if add-ons specify an icon of size 16px.

I was hoping to get 18px for the icon, as we have progress meter and in 16px the progress meter does not look good.

I have done some experiments with 16px and here are the results:
16px:
![16px](https://cloud.githubusercontent.com/assets/351062/12886340/ba177810-ce81-11e5-9095-0eadd1321882.png)

18px:
![18px](https://cloud.githubusercontent.com/assets/351062/12886342/bc586e9a-ce81-11e5-8876-341c70d1383e.png)

32px (retina display):
<img width="105" alt="32px" src="https://cloud.githubusercontent.com/assets/351062/12886347/c71765c0-ce81-11e5-8e49-ab3ffe5d3f3f.png">

36px (retina display):
<img width="144" alt="36px" src="https://cloud.githubusercontent.com/assets/351062/12886352/cd534ddc-ce81-11e5-833a-3dde57c2a886.png">

I still think the current icon which is based on 18px looks better although Firefox squeezes the icon to 16px.

>  using the css below to make it 18px

Yes, if you resize the icon to 18px, you will get the best resolution.
