### ISSUE TITLE
File name is changed from original name

### ISSUE THREAD

**Issue by d3-X-t3r** [inbasic/turbo-download-manager#30]
I downloaded a .mkv file and Turbo renamed it. It prefixed a "-" and appended a "-.mkv" at the end.
There's no other file with a similar name in my Downloads folder.

Eg: The.Name.Of.Video[abc].mkv
was renamed to:
**-**The.Name.Of.Video[abc].mkv**-.mkv**

If the file is downloaded using Chrome's built-in downloader, the name is preserved.

Turbo version: 0.2.1
Helper version: 0.1.1
Browser: Google Chrome v48.0.2564.97 (64-bit)
OS: Arch Linux (64-bit)

**Comment by inbasic** [comment]
This bug is fixed on version 0.2.3. You should get the updated version shortly.

Please reopen if you have experienced this problem on 0.2.3 as well.
