### ISSUE TITLE
chrome always uses native dialog to download

### ISSUE THREAD

**Issue by ta3pks** [inbasic/turbo-download-manager#35]
chrome always uses native dialog to download

**Comment by inbasic** [comment]
there is no way to fix this as Chrome API access is very limited. However you have tow options: either allow Chrome to start the download, then go to downloads page and copy the download link or you can install Turbo Download Manager Helper extension to send a link directly from browser's context menu.

**Comment by ta3pks** [comment]
thank you for response .
i installed helper and right click and download through that but most of the times it fails especially on redirected downloads

**Comment by inbasic** [comment]
Can you share a link as a reference. I want to see if there is any workaround

**Comment by ta3pks** [comment]
![screenshot from 2016-03-02 10-08-45](https://cloud.githubusercontent.com/assets/9097437/13453139/cca86040-e05e-11e5-9076-91e351c5e134.png)
https://dl.dropboxusercontent.com/content_link/qh9YnxuvvabCmCYVeBt0bMCC1JlY4v8849tP69V0vzNY4AJD6MCUnc7h72is2N7y/file?dl=1 this link for example

**Comment by inbasic** [comment]
So from version 0.2.4 if a download fails, you can request bypass redirects. This will fix your issue.
![screen shot 2016-03-02 at 15 46 33](https://cloud.githubusercontent.com/assets/351062/13460176/2acc9fcc-e08e-11e5-94e4-6ead9044d8fb.png)

Basically TDM tries to  extract the actual downloadable link from the provided url.
To try the developer version read FAQ 25, http://add0n.com/turbo-download-manager.html

**Comment by ta3pks** [comment]
![screenshot from 2016-03-02 16-17-18](https://cloud.githubusercontent.com/assets/9097437/13461425/4cee4d54-e092-11e5-8194-f0d4c25eb40c.png)
i installed from website and unpacked it and removed old extension but still theres no such button and chrome helper wont work with this version

**Comment by ta3pks** [comment]
and electron version doesnt seem to work too 
![screenshot from 2016-03-02 16-19-48](https://cloud.githubusercontent.com/assets/9097437/13461486/c9aa762e-e092-11e5-91dc-0b168dffac8c.png)

**Comment by inbasic** [comment]
I must have forgotten to sync the git repo
https://github.com/inbasic/turbo-download-manager/blob/master/builds/packed/chrome.zip?raw=true

Electron setup is tricky. Please open a new bug if you want to use it.
