### ISSUE TITLE
Turbo download manager not show choice.

### ISSUE THREAD

**Issue by lagun** [inbasic/turbo-download-manager#36]
this is my old thread, it have a problem like this. 
https://github.com/inbasic/turbo-download-manager/issues/22
firefox 45 32bit
i test on a clean profile, it not work and same problem.
tdm version 0.2.3 and 0.2.4

link of the webpage
http://www.filehorse.com/download-ashampoo-snap/

i try to add some extension and it support tdm show choice.
http://www12.zippyshare.com/v/lEr9BS89/file.html
watch my video.
https://sendvid.com/66u7jae5

**Comment by inbasic** [comment]
Great catch! Thanks

Can you confirm the fix on https://github.com/inbasic/turbo-download-manager/blob/master/builds/packed/firefox.xpi?raw=true

**Comment by lagun** [comment]
maybe but it not fix all problem because it work only first time ,when open browser.
if add extension for support tdm show choice, it work everytime  when i click download.
http://www12.zippyshare.com/v/lEr9BS89/file.html
watch my video to see my problem.
https://sendvid.com/d0f5r88i

**Comment by inbasic** [comment]
Thanks for the follow up. It is fixed now please try one more time;
https://github.com/inbasic/turbo-download-manager/blob/master/builds/packed/firefox.xpi?raw=true

**Comment by lagun** [comment]
Good job! it is fix. thx :)
