### ISSUE TITLE
Download pause after few minutes

### ISSUE THREAD

**Issue by ardi132** [inbasic/turbo-download-manager#37]
i'm trying to download some big files, but the download often paused after few minutes (repeatedly) so i need to resume my download every time.

**Comment by anewuser** [comment]
@ardi132  Your report is useless if you don't tell the developer what version of the extension and browser you are using, what "big files" you are trying to download (with their specific URLs) etc.

**Comment by inbasic** [comment]
@ardi132 most likely the server you are trying to download from, is sensitive to the number of simultaneous threads. Usually reducing the number of threads fixes the problem. Anyhow as @anewuser suggested it would help if you share a link.
