### ISSUE TITLE
add support for “double-click to open the file”

### ISSUE THREAD

**Issue by pangyf10** [inbasic/turbo-download-manager#39]
I think tdm should add support for “double-click to open the file”，it is very  convenient。
In firefox，“ about:downloads” have the function。

**Comment by inbasic** [comment]
There is a new button in the actions section for each item;
![screen shot 2016-04-30 at 17 52 26](https://cloud.githubusercontent.com/assets/351062/14936020/8a7774c8-0efc-11e6-9dd9-5c9b1ed27839.png)

Clicking on the hand icon will open the downloaded file.

Note that this is Firefox only feature.

**Comment by inbasic** [comment]
This feature is available on 0.2.5b3; https://github.com/inbasic/turbo-download-manager/blob/master/builds/packed/firefox.xpi?raw=true
