### ISSUE TITLE
support palemoon.

### ISSUE THREAD

**Issue by lagun** [inbasic/turbo-download-manager#44]
Developer, support palemoon plz.
Do you have plan to support palemoon?

**Comment by inbasic** [comment]
Not until Pale Moon starts supporting [JPM](https://www.npmjs.com/package/jpm). I am still not sure why Pale Moon still under CFX. It just takes too much time to rewrite all the missing modules

**Comment by inbasic** [comment]
Meanwhile you can use this downloader as an stand-alone application and integrate it into your PaleMoon through FlashGot extension as described in http://add0n.com/turbo-download-manager.html#faq26

**Comment by lagun** [comment]
Thank you.

this link http://relmirror2.palemoon.org/release/palemoon-26.2.2.win32.installer.exe
i try but tdm can't download.
http://postimg.org/image/s345dqvm9/
http://postimg.org/image/ckkhlurgx/

**Comment by inbasic** [comment]
It can download when you paste the link to the manager. Maybe the integration has a problem, right? can you send an screenshot of your FlashGot integration settings?

**Comment by lagun** [comment]
http://postimg.org/image/ckkhlurgx/

**Comment by lagun** [comment]
Now it work fine. i use v0.2.8-beta.6.

**Comment by inbasic** [comment]
Perfect! Thanks for the report. 
P.S: `v0.2.8-beta.8` is also released

**Comment by inbasic** [comment]
Version 0.3.0 seems to be stable enough to be used as an external download manager. Please open a new bug if you have integration issues with this version.
