### ISSUE TITLE
[Feature request] Play media while downloading | Play button

### ISSUE THREAD

**Issue by omar391** [inbasic/turbo-download-manager#49]
To my knowledge, **TDM already has an optimized algorithm for downloading media(audio/video format) more quickly (by creating segments more adjacently than other file formats).**

So What it would be wonderful to have following options:

> 1. A configurable option in setting to choose a system media player
> 2. A play button to play the media while it continues to download.

I have been checking and using many download manager to get such feature but TDM is the only manager that I came across to have implemented such feature. Actually, I do have a plan to check out the media file segmentation codes and optimize it for better bufferless streaming. I would love to hear from you.

**Comment by inbasic** [comment]
there are two options that can be adjusted: `obj.maxByteSize` which is the maximum length of a single fetch and `obj.threads` which is the number of concurrent segments.

Playing with these two would result in different downloading behaviors. If `obj.maxByteSize` is not set during a job submission, the default which is 20MBytes is used. This will result in many segments for a large file. Note that TDM always starts to fetch a segment with the minimum offset and hence using small  `obj.maxByteSize` is perfect for media fetching and watching.

> I do have a plan to check out the media file segmentation codes and optimize it for better bufferless streaming.

It would be great for TDM to be able to optimize these two values based on mime types. Let me know how it goes and whether it is possible to integrate it into TDM or not

P.S: this is the internal code for segmentation; https://github.com/inbasic/turbo-download-manager/blob/master/src/lib/wget.js#L433-L448

> Play media while downloading | Play button

You can actually does this. Simply let TDM finish the first few segments and then drop the file in a media player like VLC. Any media player that can open streams without blocking them would work.

**Comment by omar391** [comment]
Thanks for your references and the link on segmentation. I will look into it when time permits and let you know or make a pull request.

But overall these were/are my main objectives:

> 1. An optimised dynamic segmentation algorithm for media types based on current net speed so that user could watch the media bufferless-ly with a minimal pre-wait time. (Example: uTorrent media streaming, even though it's based on p2p protocol but underlying ideas are similar)
> 2. A play icon in the downloader or player settings options so that we wouldn't need to go to the file directory, every time to play the media.
> 3. Show a play/download button on the actual media object [html | flash] in the site like IDM does (maybe when our media grabber is implemented to some extent) to initiate the direct accelerated-streaming(downloading) task.

Let me know your thoughts!

**Comment by inbasic** [comment]
So in the new beta version ([v0.2.9-beta.2](https://github.com/inbasic/turbo-download-manager/releases)), I added a new view (preview view). The idea is to allow users to preview some types like video, audio, and pictures. Still in progress work...

**Comment by inbasic** [comment]
So a basic implementation is available on version 0.3.0. Please give it a try when it gets reviewed and open a new bug if you have a plan to submit a pull request.
