### ISSUE TITLE
RE: New permissions

### ISSUE THREAD

**Issue by Ma-XX-oN** [inbasic/turbo-download-manager#52]
What is the purpose for reading the browser history?

**Comment by inbasic** [comment]
TDM is not requesting new permission. TDM Helper does.

Note that the new requested permission is not "history". It is "management". The "history" permission was there from the first release as the extension needs to store its preferences; https://developer.chrome.com/extensions/storage

**Comment by leoj3n** [comment]
@inbasic Thanks for answering this; and what about the helper now requesting to manage apps, extensions and themes?

**Comment by Ma-XX-oN** [comment]
Oh yeah, sorry about that.  Didn't see the 'Helper' part.  Anyway, Chrome says history, not management.

![image](https://cloud.githubusercontent.com/assets/10625935/16364115/e9144f3c-3bad-11e6-895c-55d35b3bad2f.png)

I guess it doesn't say the permission difference, just all of the permissions?

**Comment by inbasic** [comment]
In the new version, helper extension opens the UI first and then send download requests. This way if TDM is not active, it will be activated. To launch an app from an extension "management" permission is required; https://developer.chrome.com/apps/management

**Comment by leoj3n** [comment]
@inbasic Interesting, thanks.
