### ISSUE TITLE
Add this option plz.

### ISSUE THREAD

**Issue by lagun** [inbasic/turbo-download-manager#6]
if possible add right click copy url and remove files from space plz

**Comment by lagun** [comment]
Add right click re-download and open folder

**Comment by inbasic** [comment]
In the latest dev version, if you click on the "i" (info) icon for each download item, a new window opens up that allow you to:
- launch file
- open containing folder
- delete file permanently

Also the actual downloadable link is available for you if re-downloading is required.

**Comment by lagun** [comment]
latest dev version is 0.1.5b3? i can't click "i" (info) icon.

**Comment by inbasic** [comment]
Try the latest version on AMO, 0.1.5

**Comment by anewuser** [comment]
@inbasic The lines in the info popup are good for advanced users, but it would be useful to have a dedicated button (on the main UI) for opening the containing folder. 

It would also be nice to have a context menu for each item, but I assume you've already considered this.

**Comment by inbasic** [comment]
For opening file or container folder it is possible to click on the icon of a download item (hover mouse for more info)

Context menu will be available soon.
