### ISSUE TITLE
Segmented Downloading Support

### ISSUE THREAD

**Issue by zero77** [inbasic/turbo-download-manager#63]
Can you add support for segmented downloading like down them all has, because this vastly increases the download speed.
Thanks

Multi-threading vs Segmented
https://whatbox.ca/wiki/Multi-threaded_and_Segmented_FTP

**Comment by inbasic** [comment]
TDM does support segmentation.

**Comment by zero77** [comment]
How do I configure segmenting as I can only see options for Multi-threading and the option to separately download more than one file at once.

Also, where dues it tell you how many segments are being downloaded currently.

Thanks

**Comment by zero77** [comment]
Yes, sorry you are right.
