### ISSUE TITLE
Use FF download folder by default

### ISSUE THREAD

**Issue by infectormp** [inbasic/turbo-download-manager#7]
By default TDM use C:\Users\%USERNAME%\Downloads\ for download files. I think if in FF used `Save files to` TDM must download files to this location.

**Comment by inbasic** [comment]
This issue is now fixed on the latest dev version,
https://github.com/inbasic/turbo-download-manager/blob/master/src.safariextension/executables/extension.xpi?raw=true

You can try it by downloading the XPI. Then drop it into your Firefox browser
