### ISSUE TITLE
downloads pause

### ISSUE THREAD

**Issue by johnothwolo** [inbasic/turbo-download-manager#8]
downloads automatically pause on their own although I haven't tried restarting because the file is hug and my wifi's kinda slow

**Comment by inbasic** [comment]
This issue is fixed on the latest dev version. Please try version 0.1.7b1,
https://github.com/inbasic/turbo-download-manager/blob/master/src.safariextension/executables/extension.xpi?raw=true

Download the XPI and drop it into your Firefox browser
